apiVersion: v1
kind: Pod
metadata:
  name: {{ .Release.Name }}
  namespace: default
spec:
  restartPolicy: "Never"
  containers:
  - name: example2
    image: busybox:1.34.0
    imagePullPolicy: IfNotPresent
    command:
    - sh
    - -c
    - |
      #!/usr/bin/env sh
      set -ex

      while :
      do
          echo "{{ .Values.message }}"
          sleep 5
      done

