apiVersion: v1
kind: Pod
metadata:
  name: {{ .Release.Name }}
  namespace: default
spec:
  restartPolicy: "Never"
  containers:
  - name: example1
    image: "{{ .Values.image.name }}:{{ .Values.image.tag }}"
    imagePullPolicy: IfNotPresent
